parameters:
#    submod_test.example.class: Toga\Bundle\SubmodTestBundle\Example

services:
#    submod_test.example:
#        class: %submod_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
